version: '3'
services:
  db-user-api:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: user-api